#!/bin/bash
# Simple deployment script for Render.com

echo "🚀 Jasmin SMS Gateway - Render.com Deployment"
echo "=============================================="
echo ""
echo "📋 Follow these steps to deploy:"
echo ""
echo "1. 🌐 Go to: https://render.com"
echo "2. 🔐 Sign up/Login with GitHub"
echo "3. ➕ Click 'New +' → 'Blueprint'"
echo "4. 🔗 Connect your GitHub repository"
echo "5. 📁 Select this repository and branch"
echo "6. ⚙️  Render will automatically detect render.yaml"
echo "7. 🚀 Click 'Apply' to deploy"
echo ""
echo "📱 After deployment, your SMS gateway will be available at:"
echo "  - HTTP API: https://your-service-name.onrender.com"
echo "  - Management CLI: telnet your-service-name.onrender.com 8990"
echo "  - SMPP Server: your-service-name.onrender.com:2775"
echo ""
echo "🔧 Next steps:"
echo "  1. Wait for deployment to complete (5-10 minutes)"
echo "  2. Check the Render dashboard for service URLs"
echo "  3. Connect to Management CLI to configure users"
echo "  4. Start sending SMS!"
echo ""
echo "📚 For detailed instructions, see DEPLOY-RENDER.md"
