services:
  - type: web
    name: jasmin-sms-gateway
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /ping
    envVars:
      - key: REDIS_CLIENT_HOST
        value: redis
      - key: AMQP_BROKER_HOST
        value: rabbit-mq
      - key: JCLI_ADMIN_USER
        value: jcliadmin
      - key: JCLI_ADMIN_PASS
        value: jclipwd
    scaling:
      minInstances: 1
      maxInstances: 1

  - type: redis
    name: jasmin-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: jasmin-rabbitmq
    env: docker
    dockerfilePath: ./Dockerfile.rabbitmq
    plan: starter
    region: oregon
    branch: main
    scaling:
      minInstances: 1
      maxInstances: 1
