#!/bin/bash
# Quick deployment script for Google Cloud Platform

echo "☁️  Jasmin SMS Gateway - Quick Google Cloud Deployment"
echo "======================================================"

echo "📋 Step 1: Create Google Cloud Project"
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Click 'Select a project' → 'New Project'"
echo "3. Name: 'jasmin-sms-gateway'"
echo "4. Click 'Create'"
echo ""

echo "📋 Step 2: Enable Billing"
echo "1. Go to 'Billing' in the left menu"
echo "2. Link a billing account (required for free tier)"
echo "3. You won't be charged for free tier usage"
echo ""

echo "📋 Step 3: Create VM Instance"
echo "1. Go to 'Compute Engine' → 'VM instances'"
echo "2. Click 'Create Instance'"
echo "3. Configure:"
echo "   - Name: jasmin-sms-gateway"
echo "   - Region: us-central1 (Iowa)"
echo "   - Zone: us-central1-a"
echo "   - Machine type: e2-micro (1 vCPU, 1GB RAM)"
echo "   - Boot disk: Ubuntu 22.04 LTS"
echo "   - Firewall: Allow HTTP traffic, Allow HTTPS traffic"
echo "4. Click 'Create'"
echo ""

echo "📋 Step 4: Configure Firewall Rules"
echo "1. Go to 'VPC network' → 'Firewall'"
echo "2. Click 'Create Firewall Rule'"
echo "3. Configure:"
echo "   - Name: jasmin-sms-gateway"
echo "   - Targets: All instances in the network"
echo "   - Source IP ranges: 0.0.0.0/0"
echo "   - Protocols and ports: TCP ports 22, 1401, 8990, 2775, 15672"
echo "4. Click 'Create'"
echo ""

echo "📋 Step 5: Connect to VM"
echo "1. Click 'SSH' button next to your VM instance"
echo "2. Or use gcloud command:"
echo "   gcloud compute ssh jasmin-sms-gateway --zone=us-central1-a"
echo ""

echo "📋 Step 6: Deploy Jasmin SMS Gateway"
echo "Run this command in your VM:"
echo "curl -s https://raw.githubusercontent.com/Arnobrizwan/Jasmin-SMS-Gateway-setup/main/jasmin-docker/deploy-gcp.sh | bash"
echo ""

echo "📋 Step 7: Test Your Deployment"
echo "After deployment, run these commands in your VM:"
echo "make status                    # Check service status"
echo "sudo cat /etc/jasmin/.env     # Get credentials"
echo "curl http://localhost:1401/ping  # Test HTTP API"
echo "make cli                      # Connect to Management CLI"
echo ""

echo "🎉 Your SMS Gateway will be running at:"
echo "HTTP API: http://YOUR_VM_EXTERNAL_IP:1401"
echo "Management CLI: telnet YOUR_VM_EXTERNAL_IP 8990"
echo "SMPP Server: YOUR_VM_EXTERNAL_IP:2775"
echo "RabbitMQ Management: http://YOUR_VM_EXTERNAL_IP:15672"
echo ""

echo "📚 For detailed instructions, see:"
echo "- README.md - Complete usage guide"
echo "- GCP-DEPLOY.md - Step-by-step deployment"
echo "- SECURITY.md - Security best practices"
echo ""

echo "🚀 Ready to deploy! Follow the steps above."
